# Generated by Django 5.0.7 on 2024-07-16 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cadastroEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeEmp', models.CharField(max_length=255)),
                ('razaoSocialEmp', models.CharField(max_length=255)),
                ('cnpjEmp', models.CharField(max_length=255)),
                ('inscEstEmp', models.CharField(max_length=255)),
                ('cepEmp', models.CharField(max_length=9)),
                ('lougradouroEmp', models.CharField(max_length=255)),
                ('numeroEmp', models.CharField(max_length=5)),
                ('bairroEmp', models.CharField(max_length=255)),
                ('cidadeEmp', models.CharField(max_length=100)),
                ('estadoEmp', models.CharField(max_length=4)),
                ('telefoneEmp', models.CharField(max_length=16)),
                ('celularEmp', models.CharField(max_length=16)),
                ('pessoaContEmp', models.CharField(max_length=50)),
                ('emailEmp', models.CharField(max_length=50)),
                ('isentoTribEmp', models.CharField(max_length=5)),
                ('taxaAdmEmp', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='cadastroMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=260)),
                ('especialidade', models.CharField(max_length=100)),
                ('crm', models.CharField(max_length=10)),
                ('telefone', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='plantao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('medico', models.CharField(max_length=260)),
                ('hora', models.TimeField()),
                ('valor', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='valorPlantao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valorPlantao_12', models.CharField(max_length=10)),
                ('valorPlantaoHora', models.CharField(max_length=10)),
                ('valorPlantaoSemana', models.CharField(max_length=10)),
                ('valorPlantaoSabDom', models.CharField(max_length=10)),
            ],
        ),
    ]
