# Generated by Django 5.0.7 on 2024-07-17 00:39

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atendente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CadastroEmpresa',
            fields=[
                ('nome', models.CharField(max_length=255)),
                ('razao_social', models.CharField(max_length=255)),
                ('cnpj', models.CharField(max_length=14, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='CNPJ deve conter 14 dígitos numéricos', regex='^\\d{14}$')])),
                ('inscricao_estadual', models.CharField(max_length=255)),
                ('cep', models.CharField(max_length=9, validators=[django.core.validators.RegexValidator(message='CEP deve estar no formato XXXXX-XXX', regex='^\\d{5}-?\\d{3}$')])),
                ('logradouro', models.CharField(max_length=255)),
                ('numero', models.CharField(max_length=5)),
                ('bairro', models.CharField(max_length=255)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=2)),
                ('telefone', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(message='Telefone deve estar no formato (XX) XXXX-XXXX ou (XX) XXXXX-XXXX', regex='^\\(?\\d{2}\\)?[\\s-]?\\d{4,5}-?\\d{4}$')])),
                ('celular', models.CharField(default='00000000000', max_length=16, validators=[django.core.validators.RegexValidator(message='Celular deve estar no formato (XX) XXXXX-XXXX', regex='^\\(?\\d{2}\\)?[\\s-]?\\d{4,5}-?\\d{4}$')])),
                ('pessoa_contato', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50, validators=[django.core.validators.EmailValidator(message='Email inválido')])),
                ('isento_tributacao', models.BooleanField(default=False)),
                ('taxa_administrativa', models.DecimalField(decimal_places=2, max_digits=6)),
                ('valor_imposto', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='InformacoesBancarias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banco', models.CharField(max_length=50)),
                ('agencia', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Agência deve conter de 4 a 10 dígitos numéricos', regex='^\\d{4,10}$')])),
                ('conta', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Conta deve conter de 5 a 10 dígitos numéricos', regex='^\\d{5,10}$')])),
                ('titular_conta', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ValorPlantao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_12h', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_por_hora', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_semana', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_fim_semana', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='CadastroMedico',
            fields=[
                ('nome', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=14, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='CPF deve conter 11 dígitos numéricos', regex='^\\d{11}$')])),
                ('especialidade', models.CharField(max_length=100)),
                ('crm', models.CharField(max_length=20)),
                ('celular', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(message='Celular deve estar no formato (XX) XXXXX-XXXX', regex='^\\(?\\d{2}\\)?[\\s-]?\\d{4,5}-?\\d{4}$')])),
                ('logradouro', models.CharField(max_length=255)),
                ('numero', models.CharField(max_length=5)),
                ('complemento', models.CharField(blank=True, max_length=255, null=True)),
                ('bairro', models.CharField(max_length=255)),
                ('cidade', models.CharField(max_length=255)),
                ('estado', models.CharField(max_length=2)),
                ('telefone1', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(message='Telefone deve estar no formato (XX) XXXX-XXXX ou (XX) XXXXX-XXXX', regex='^\\(?\\d{2}\\)?[\\s-]?\\d{4,5}-?\\d{4}$')])),
                ('telefone2', models.CharField(blank=True, max_length=16, null=True, validators=[django.core.validators.RegexValidator(message='Telefone deve estar no formato (XX) XXXX-XXXX ou (XX) XXXXX-XXXX', regex='^\\(?\\d{2}\\)?[\\s-]?\\d{4,5}-?\\d{4}$')])),
                ('email', models.EmailField(max_length=100, validators=[django.core.validators.EmailValidator(message='Email inválido')])),
                ('informacoes_bancarias', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.informacoesbancarias')),
            ],
        ),
        migrations.CreateModel(
            name='InformacoesClinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('telefone', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(message='Telefone deve estar no formato (XX) XXXX-XXXX ou (XX) XXXXX-XXXX', regex='^\\(?\\d{2}\\)?[\\s-]?\\d{4,5}-?\\d{4}$')])),
                ('atendentes', models.ManyToManyField(related_name='clinicas', to='home.atendente')),
            ],
        ),
        migrations.CreateModel(
            name='Plantao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField(default=django.utils.timezone.now)),
                ('hora_inicio', models.TimeField(default=django.utils.timezone.now)),
                ('data_termino', models.DateField(default=django.utils.timezone.now)),
                ('hora_termino', models.TimeField(default=django.utils.timezone.now)),
                ('especialidade', models.CharField(max_length=255)),
                ('tipo_plantao', models.CharField(max_length=20)),
                ('quantidade_horas', models.DecimalField(decimal_places=2, max_digits=5)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(max_length=12)),
                ('contato_emergencia', models.CharField(max_length=255)),
                ('equipamentos_necessarios', models.TextField()),
                ('cargos_auxiliares', models.TextField()),
                ('substituto', models.CharField(max_length=255)),
                ('observacoes', models.TextField(max_length=255)),
                ('medico_responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.cadastromedico')),
            ],
        ),
    ]
