# Generated by Django 5.0.7 on 2024-07-18 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastroempresa',
            name='taxa_administrativa',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
