# Generated by Django 5.1.2 on 2024-10-30 18:18

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CadastroEmpresa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome_fantasia', models.CharField(default='N/A', max_length=255)),
                ('razao_social', models.CharField(default='N/A', max_length=255)),
                ('cnpj', models.CharField(max_length=18, unique=True, validators=[django.core.validators.RegexValidator(message='CNPJ deve estar no formato 00.000.000/0000-00', regex='^\\d{2}\\.\\d{3}\\.\\d{3}/\\d{4}-\\d{2}$')])),
                ('inscricao_estadual', models.CharField(blank=True, max_length=30, null=True)),
                ('Inscricao_municipal', models.CharField(blank=True, max_length=30, null=True)),
                ('cep', models.CharField(max_length=9, validators=[django.core.validators.RegexValidator(message='CEP deve estar no formato XXXXX-XXX', regex='^\\d{5}-?\\d{3}$')])),
                ('logradouro', models.CharField(max_length=255)),
                ('numero', models.CharField(max_length=5)),
                ('bairro', models.CharField(max_length=255)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=2)),
                ('telefone', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(message='Telefone deve estar no formato (XX) XXXX-XXXX ou (XX) XXXXX-XXXX', regex='^\\(?\\d{2}\\)?[\\s-]?\\d{4,5}-?\\d{4}$')])),
                ('celular', models.CharField(blank=True, max_length=16, null=True, validators=[django.core.validators.RegexValidator(message='Celular deve estar no formato (XX) XXXXX-XXXX', regex='^\\(?\\d{2}\\)?[\\s-]?\\d{4,5}-?\\d{4}$')])),
                ('email', models.EmailField(max_length=50, validators=[django.core.validators.EmailValidator(message='Email inválido')])),
                ('isento_tributacao', models.BooleanField(default=False)),
                ('pessoa_contato', models.CharField(default='N/A', max_length=50)),
                ('valor_12h', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('valor_por_hora', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('valor_semana', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('valor_fim_semana', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('taxa_administrativa', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('valor_contrato', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CadastroMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctorCpf', models.CharField(default='N/A', max_length=11, unique=True)),
                ('doctorName', models.CharField(default='N/A', max_length=100)),
                ('birthdate', models.DateField(default=django.utils.timezone.now)),
                ('email', models.EmailField(default='N/A', max_length=254)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('cep', models.CharField(blank=True, max_length=9, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('number', models.CharField(blank=True, max_length=10, null=True)),
                ('complement', models.CharField(blank=True, max_length=255, null=True)),
                ('bairro', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=2, null=True)),
                ('professionalType', models.CharField(blank=True, max_length=50, null=True)),
                ('doctorSpecialty', models.CharField(blank=True, max_length=100, null=True)),
                ('registerType', models.CharField(blank=True, max_length=50, null=True)),
                ('doctorCrm', models.CharField(default='N/A', max_length=15, unique=True)),
                ('academicDegree', models.CharField(blank=True, max_length=100, null=True)),
                ('institutionName', models.CharField(default='N/A', max_length=255)),
                ('graduationYear', models.IntegerField(default=2000)),
                ('certifications', models.TextField(blank=True, null=True)),
                ('clinicAffiliation', models.CharField(blank=True, max_length=255, null=True)),
                ('otherInfo', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plantao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data_inicio', models.DateField(default=django.utils.timezone.now)),
                ('hora_inicio', models.TimeField(default=django.utils.timezone.now)),
                ('data_termino', models.DateField(default=django.utils.timezone.now)),
                ('hora_termino', models.TimeField(default=django.utils.timezone.now)),
                ('especialidade', models.CharField(max_length=255)),
                ('tipo_plantao', models.CharField(max_length=20)),
                ('quantidade_horas', models.DecimalField(decimal_places=2, max_digits=5)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(max_length=12)),
                ('contato_emergencia', models.CharField(max_length=255)),
                ('equipamentos_necessarios', models.TextField(blank=True, null=True)),
                ('cargos_auxiliares', models.TextField(blank=True, null=True)),
                ('substituto', models.CharField(blank=True, max_length=255, null=True)),
                ('observacoes', models.TextField(blank=True, max_length=255, null=True)),
                ('medico_responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plantoes', to='home.cadastromedico')),
            ],
        ),
        migrations.CreateModel(
            name='PrintPlantao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=14)),
                ('especialidade', models.CharField(max_length=100)),
                ('valor_plantao', models.CharField(max_length=100)),
                ('horas', models.CharField(max_length=100)),
                ('valor_horas', models.CharField(max_length=100)),
                ('subtotal', models.CharField(max_length=100)),
                ('valor_imposto', models.CharField(max_length=100)),
                ('valor_a_receber', models.CharField(max_length=100)),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('medico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.cadastromedico')),
            ],
        ),
    ]
