# Generated by Django 5.0.7 on 2024-07-16 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_delete_cadastromedico_delete_plantao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastroempresa',
            name='taxaAdmEmp',
            field=models.CharField(max_length=6),
        ),
    ]
