# Generated by Django 5.0.7 on 2024-07-19 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_cadastroempresa_taxa_administrativa'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ValorPlantao',
        ),
        migrations.AddField(
            model_name='cadastroempresa',
            name='valor_12h',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='cadastroempresa',
            name='valor_fim_semana',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='cadastroempresa',
            name='valor_por_hora',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='cadastroempresa',
            name='valor_semana',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
