# Generated by Django 5.0.7 on 2024-09-07 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_printplantao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printplantao',
            name='horas',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='printplantao',
            name='subtotal',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='printplantao',
            name='valor_a_receber',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='printplantao',
            name='valor_horas',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='printplantao',
            name='valor_imposto',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='printplantao',
            name='valor_plantao',
            field=models.IntegerField(),
        ),
    ]
