# Generated by Django 5.0.7 on 2024-07-21 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_delete_valorplantao_cadastroempresa_valor_12h_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informacoesclinica',
            name='atendentes',
        ),
        migrations.RemoveField(
            model_name='cadastromedico',
            name='informacoes_bancarias',
        ),
        migrations.AddField(
            model_name='cadastromedico',
            name='agencia',
            field=models.CharField(default='Agencia', max_length=10),
        ),
        migrations.AddField(
            model_name='cadastromedico',
            name='banco',
            field=models.CharField(default='Banco', max_length=50),
        ),
        migrations.AddField(
            model_name='cadastromedico',
            name='conta',
            field=models.CharField(default='Conta', max_length=10),
        ),
        migrations.AddField(
            model_name='cadastromedico',
            name='nomeAtendente',
            field=models.CharField(default='Nome Atendente', max_length=255),
        ),
        migrations.AddField(
            model_name='cadastromedico',
            name='nomeClinica',
            field=models.CharField(default='Nome Atendente', max_length=255),
        ),
        migrations.AddField(
            model_name='cadastromedico',
            name='telefone',
            field=models.CharField(default='Telefone', max_length=16),
        ),
        migrations.AddField(
            model_name='cadastromedico',
            name='titular_conta',
            field=models.CharField(default='Titular', max_length=255),
        ),
        migrations.AlterField(
            model_name='cadastromedico',
            name='celular',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='cadastromedico',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cadastromedico',
            name='telefone1',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='cadastromedico',
            name='telefone2',
            field=models.CharField(max_length=16),
        ),
        migrations.DeleteModel(
            name='Atendente',
        ),
        migrations.DeleteModel(
            name='InformacoesClinica',
        ),
        migrations.DeleteModel(
            name='InformacoesBancarias',
        ),
    ]
