# Generated by Django 5.0.7 on 2024-09-07 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_printplantao_horas_alter_printplantao_subtotal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printplantao',
            name='horas',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='printplantao',
            name='subtotal',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='printplantao',
            name='valor_a_receber',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='printplantao',
            name='valor_horas',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='printplantao',
            name='valor_imposto',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='printplantao',
            name='valor_plantao',
            field=models.CharField(max_length=100),
        ),
    ]
