# Generated by Django 5.0.7 on 2024-07-22 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_informacoesclinica_atendentes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantao',
            name='medico_responsavel',
            field=models.CharField(max_length=255),
        ),
    ]
