# Generated by Django 5.0.7 on 2024-09-20 02:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_printplantao_horas_alter_printplantao_subtotal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='printplantao',
            name='medico',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.cadastromedico'),
        ),
    ]
