# Generated by Django 5.0.7 on 2024-09-20 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_printplantao_medico'),
    ]

    operations = [
        migrations.AddField(
            model_name='printplantao',
            name='data',
            field=models.DateField(blank=True, null=True),
        ),
    ]
